# Generated by Django 3.1.1 on 2020-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='page',
            field=models.CharField(choices=[('q-comp_t', 'Computational Thinking'), ('q-data_r', 'Data Representation'), ('q-algo', 'algorithms'), ('q-code', 'Code')], default='comp_t', max_length=10),
        ),
    ]
