# Generated by Django 3.1.1 on 2020-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200924_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='op1',
            new_name='opt1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='op2',
            new_name='opt2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='op3',
            new_name='opt3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='op4',
            new_name='opt4',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(choices=[('opt1', 'Option 1'), ('opt2', 'Option 2'), ('opt3', 'Option 3'), ('opt4', 'Option 4')]),
        ),
    ]
