# Generated by Django 3.1.1 on 2020-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200924_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qn_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(choices=[('opt1', 'Option 1'), ('opt2', 'Option 2'), ('opt3', 'Option 3'), ('opt4', 'Option 4')], default='opt1'),
        ),
    ]
