# Generated by Django 3.1.1 on 2020-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0006_auto_20200924_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='qn_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
