# Generated by Django 3.1.1 on 2020-09-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=25)),
                ('quote', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
