# Generated by Django 3.1.1 on 2020-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='pengguna', max_length=30),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Anonim', max_length=25),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(max_length=100),
        ),
    ]
