# Generated by Django 3.1.1 on 2020-09-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('curriculum', '0005_comment_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.CharField(choices=[('comp_t', 'Computational Thinking'), ('data_r', 'Data Representation'),
                                            ('algo', 'Algorithms'), ('code', 'Code')], default='comp_t', max_length=10),
        ),
    ]
